version: "3"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IS_REMOTE=true
    env_file:
      - .env
    working_dir: /ta_framework
    volumes:
      - ${PWD}/reports:/ta_framework/reports

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.3.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
